 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.phantomz3;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

@Environment(EnvType.CLIENT)
public class LifestealModClient implements ClientModInitializer {
   public void onInitializeClient() {
   }
}
