 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.phantomz3;

import me.shedaniel.autoconfig.ConfigData;
import me.shedaniel.autoconfig.annotation.Config;

@Config(
   name = "lifestealmod"
)
public class ModConfig implements ConfigData {
   public int maxHeartCap = 40;
   public boolean disableEnderPearl = true;
   public boolean disableCPVP = true;
   public boolean disableTotem = true;
   public boolean disableNetherite = true;
   public boolean noDragonEggEnderChest = true;
   public int riptideCooldown = 200;
   public boolean riptideCooldownEnabled = true;
   public boolean preventNaturalHeartLoss = false;
}
