 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.phantomz3;

import net.minecraft.class_1277;
import net.minecraft.class_1657;
import net.minecraft.class_1661;
import net.minecraft.class_1707;
import net.minecraft.class_1713;
import net.minecraft.class_1735;
import net.minecraft.class_1799;
import net.minecraft.class_3222;
import net.minecraft.class_3917;

public class RecipeScreenHandler extends class_1707 {
   public RecipeScreenHandler(int syncId, class_1661 playerInventory, class_1277 inventory) {
      super(class_3917.field_18667, syncId, playerInventory, inventory, 5);
   }

   public boolean method_7597(class_1657 player) {
      return true;
   }

   public boolean method_7613(class_1799 stack, class_1735 slot) {
      return false;
   }

   public void method_7593(int slotId, int button, class_1713 actionType, class_1657 player) {
      class_1799 clickedStack = ((class_1735)this.field_7761.get(slotId)).method_7677();
      if (clickedStack != class_1799.field_8037) {
         ((class_3222)player).method_7346();
      }

   }
}
