 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.phantomz3;

import net.minecraft.class_124;
import net.minecraft.class_1277;
import net.minecraft.class_1657;
import net.minecraft.class_1661;
import net.minecraft.class_1707;
import net.minecraft.class_1713;
import net.minecraft.class_1735;
import net.minecraft.class_1799;
import net.minecraft.class_1802;
import net.minecraft.class_1934;
import net.minecraft.class_2561;
import net.minecraft.class_3222;
import net.minecraft.class_3917;
import net.minecraft.class_5134;
import net.minecraft.class_9334;

public class ReviveScreenHandler extends class_1707 {
   public ReviveScreenHandler(int syncId, class_1661 playerInventory, class_1277 inventory) {
      super(class_3917.field_17326, syncId, playerInventory, inventory, 3);
   }

   public boolean method_7597(class_1657 player) {
      return true;
   }

   public boolean method_7613(class_1799 stack, class_1735 slot) {
      return false;
   }

   public void method_7593(int slotId, int button, class_1713 actionType, class_1657 player) {
      class_1799 clickedStack = ((class_1735)this.field_7761.get(slotId)).method_7677();
      if (clickedStack.method_7909() == class_1802.field_8575) {
         String playerName = ((class_2561)clickedStack.method_57824(class_9334.field_50239)).getString();
         class_3222 target = ((class_3222)player).method_5682().method_3760().method_14566(playerName);
         if (target != null) {
            this.executeRevive_((class_3222)player, target, false);
            ((class_1735)this.field_7761.get(slotId)).method_53512(class_1799.field_8037);
            this.method_7623();
            ((class_3222)player).method_7346();
         }
      }

      if (clickedStack.method_7909() == class_1802.field_8871) {
         ((class_3222)player).method_7346();
      }

      super.method_7593(slotId, button, actionType, player);
   }

   private int executeRevive_(class_3222 player, class_3222 target, boolean isOpRevive) {
      if (player != target && !(target.method_6032() > 2.0F)) {
         double currentMaxHealth = target.method_45326(class_5134.field_23716);
         double newMaxHealth = Math.max(2.0D, currentMaxHealth + 8.0D);
         target.method_5996(class_5134.field_23716).method_6192(newMaxHealth);
         target.method_6033((float)newMaxHealth);
         target.method_7336(class_1934.field_9215);
         player.method_7353(class_2561.method_43470("Succesfully revived the player!").method_27692(class_124.field_1060), true);

         for(int i = 0; i < player.method_31548().method_5439(); ++i) {
            class_1799 itemStack = player.method_31548().method_5438(i);
            if (itemStack.method_7909() == class_1802.field_8668 && itemStack.method_7958() && itemStack.method_7964().getString().equals("Revive Beacon")) {
               itemStack.method_7934(1);
               break;
            }
         }

         return 1;
      } else {
         player.method_7353(class_2561.method_43470("Reviving the player failed!").method_27692(class_124.field_1061), true);
         return 0;
      }
   }
}
