name: Build lifestealmod.jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod .jar
        run: ./gradlew build --no-daemon

      - name: Upload mod artifact
        uses: actions/upload-artifact@v4
        with:
          name: lifestealmod
          path: build/libs/*.jar
